### ISSUE TITLE
Erro puxando CAGED

### ISSUE THREAD

**Issue by fernandes-rodrigo** [guilhermejacob/guilhermejacob.github.io#1]
Olá, Guilherme. Estou tentando fazer o que você vez em: [https://guilhermejacob.github.io/2017/11/rais-caged-r/](url) 
Mas quando chego na parte
`downloader::source_url( "https://github.com/guilhermejacob/guilhermejacob.github.io/blob/master/scripts/mtps.R" )
`
Eu tenho o erro 

```
Not checking SHA-1 of downloaded file.
Error in source(temp_file, ...) : 
  C:\Users\Rod\AppData\Local\Temp\RtmpQDofGl\file35a01981a6f:7:1: unexpected '<'
6: 
7: <
   ^
```
Sou relativamente novo no R, mais ainda no que se refere a criar funções. Você faz ideia do que pode ter acontecido?
Obrigado!

**Comment by guilhermejacob** [comment]
Fiz algumas alterações no arquivo neste commit 71f18422896a30d58bb6d6ed97ffbe71ada6f1d6. Sugiro que você tente com essa nova versão e instale as libraries quando for neccessário.

**Comment by fernandes-rodrigo** [comment]
Fala, Guilherme! Os pacotes estão instalados.
Continuo tendo o mesmo erro e no mesmo lugar.
```
> downloader::source_url( "https://github.com/guilhermejacob/guilhermejacob.github.io/blob/master/scripts/mtps.R" )
 No SHA-1 hash specified for the file. The hash is needed to ensure that
 the file at the URL has not changed. See ?source_url for information on
 why this is useful. Are sure you want to continue? [y/n] y
trying URL 'https://github.com/guilhermejacob/guilhermejacob.github.io/blob/master/scripts/mtps.R'
Content type 'text/html; charset=utf-8' length unknown
downloaded 190 KB

Not checking SHA-1 of downloaded file.
Error in source(temp_file, ...) : 
  C:\Users\Rod\AppData\Local\Temp\RtmpeAwat3\file4d7867294344:7:1: unexpected '<'
6: 
7: <
   ^
```
Obrigado pela resposta, não imaginaria que após 2 anos iria obtê-la!

**Comment by guilhermejacob** [comment]
Acho que já sei qual é o problema. Ainda não ajustei no site, mas rode esse comando:
```
downloader::source_url( "https://raw.githubusercontent.com/guilhermejacob/guilhermejacob.github.io/master/scripts/mtps.R" , prompt = FALSE )
```

**Comment by fernandes-rodrigo** [comment]
Certo, ai funcionou mas ai eu obtenho outros erros:
```
> catalog <- catalog_mtps( output_dir = output_dir )
 Error in library(future.apply) : 
  there is no package called ‘future.apply’ 
> catalog <- datavault_mtps( catalog = catalog, datavault_dir = datavault_dir )
 Error in tolower(catalog$full_url) : object 'catalog' not found 
```
O pacote "archive" não existe mais, não sei se essa é a razão do erro.

**Comment by guilhermejacob** [comment]
O `future.apply` existe no CRAN, então: `install.packages("future.apply")`

O pacote `archive` não existe no CRAN, mas existe no [GitHub do autor](https://github.com/jimhester/archive). Você pode instalar usando:
```
devtools::install_github("jimhester/archive")
```
Provavelmente, vai precisar fazer o mesmo com o MonetDBLite: `devtools::install_github("hannesmuehleisen/MonetDBLite-R")`.

**Comment by fernandes-rodrigo** [comment]
```
> catalog <- catalog_mtps( output_dir = output_dir )
3 new directories found.
Error in function (type, msg, asError = TRUE)  : 
  Illegal characters found in URL
Called from: resignalConditions(future)
```
O complicado é que agora eu já não entendo mais nada que tá acontecendo hehe

**Comment by guilhermejacob** [comment]
Você tá usando Windows?

**Comment by fernandes-rodrigo** [comment]
Sim! É esse o problema?

**Comment by guilhermejacob** [comment]
Não deveria ser. Mas fica mais fácil de descobrir. Vou tentar rodar no Windows e volto.

**Comment by guilhermejacob** [comment]
Mudei um pouco do código. Acho que agora vai.

**Comment by fernandes-rodrigo** [comment]
Foi. Muito obrigado, Guilherme, e parabéns pelo trabalho!

**Comment by guilhermejacob** [comment]
Disponha! Vou fechar a issue.
