### ISSUE TITLE
Erro com build_mtps - " object 'uf' not found "

### ISSUE THREAD

**Issue by giovannachaves** [guilhermejacob/guilhermejacob.github.io#2]
Estou tentando montar a base de dados com RAIS e CAGED de 1997 a 2018, seguindo o passo a passo em https://guilhermejacob.github.io/2017/11/rais-caged-r/. Tudo indo certo até chegar na parte de realmente construir a base, 
`build_mtps( catalog = catalog ) `

Aparece o seguinte erro:
_Error in eval(jsub, SDenv, parent.frame()) : object 'uf' not found_ 

Alguém sabe o que pode ter acontecido e como resolver? O resto rodou direitinho então imagino que os arquivos baixaram certo, não entendi pq não está localizando 'uf' mas também não consigo acessar o arquivo original.

Obrigada desde já!

**Comment by guilhermejacob** [comment]
Desculpa a demora (sua issue está quase aniversariando). Fiquei enrolado com as coisas do mestrado e acabei não conseguindo acompanhar aqui. Vou verificar o que está acontecendo e volto.

Você conseguiu resolver?

**Comment by giovannachaves** [comment]
Oi Guilherme!

Que isso, sem problemas. Já não me lembro exatamente o que tentei para resolver mas não tive muita sorte; acabei buscando os dados diretamente no site e fazendo o download dos que eu precisava. Se você conseguir descobrir, acho que ainda será bastante útil!

**Comment by guilhermejacob** [comment]
@giovannachaves , subi outra versão do código agora. Testei com 2016 e parece que funciona. 
Acho que vou trabalhar no "novo CAGED" mês que vem e posso resolver se houver outros problemas.

Vou fechar essa issue, mas pode reabrir se tiver algum problema.
