### ISSUE TITLE
Agradecimento e pergunta sobre problema com CadUnico 2018

### ISSUE THREAD

**Issue by rodrigoesborges** [guilhermejacob/guilhermejacob.github.io#3]
Prezado Guilherme,

Antes de mais nada agradecer sua amabilidade em compartilhar ensinamentos e código. 

Parece que há problema com os pesos , já que a extrapolação para 2018, utilizando o script sem alterações, oferece dados impossíveis.

Fazendo o mesmo sugerido em
https://guilhermejacob.github.io/2017/11/amostra-cadunico-r/

Para testar, com dados de 2018, obtive:
                                    total                  SE
I(idade < 18)FALSE 3970821348406225534976  998407427978747904
I(idade < 18)TRUE  2872606439493932154880 1480169200339997184

Obviamente não bate. Vou averiguar para tentar sugerir solução para o problema.

Para o caso de 2016 funciona conforme o artigo referido de seu site (pequena variação nos dados, acredito que a fonte foi atualizada após a escrita).

**Comment by rodrigoesborges** [comment]
Parece que o arquivo de microdados 2018 veio com pesos errados, sem vírgula

**Comment by iagocnunes** [comment]
Eu também estou com esse problema. Você conseguiu resolver @rodrigoesborges ?

**Comment by guilhermejacob** [comment]
Desculpa, gente. Eu devo ter perdido isso aqui no meio dos meus e-mails. Vou dar uma olhada no que está acontecendo.

**Comment by iagocnunes** [comment]
É só que os pesos na base de 2018 vieram sem virgula, eu tentei formatar pelo pacote "gt" mas eu não domino as funções desse pacote, devo estar pedindo errado a sequência

**Comment by guilhermejacob** [comment]
Eu estou trabalhando numa solução "provisória" aqui. Se você multiplica os pesos por `1e-14`, o problema é resolvido, aparentemente. Vou subir o código e reescrever parte do post com o novo exemplo.

A melhor solução seria enviar um e-mail para o pessoal da SAGI, indicando que existe este problema na base de dados deles. Essas coisas costumam acontecer e, em geral, são fáceis de resolver. Se fosse no IBGE, eu mesmo comunicaria, mas não conheço os canais da SAGI.

@rodrigoesborges ou @iagocnunes , conhecem algum canal lá? Poderiam enviar um e-mail?

**Comment by iagocnunes** [comment]
Também não conheço ninguém lá, mas eu resolvi a questão com ifelse, subi aqui:
https://github.com/iagocnunes/Cadunico/blob/main/cadunico%20plano.R
Mas eu ainda preciso trabalhar melhor essa rotina, os valores da coluna de 1 me retornam normais com svytotal, mas svytotal da variável "sabe ler ou escrever" me retornam NA... Talvez seja meu pc aqui do trabalho que não está aguentando o banco ou algum problema no código que escrevi, ainda vou resolver isso... mas os pesos eu sei que estão ok!
Abraços!

**Comment by iagocnunes** [comment]
Puts, agora que eu reparei que esqueci de por na.rm=T no svytotal. A rotina tá 100% boa

**Comment by guilhermejacob** [comment]
Coloquei outra versão do código lá no site lá no site; parece estar funcionando. Qualquer coisa, pode reabrir aqui.
